logging.level:
  de.n04r.homecontrol: DEBUG

scenes:
  - name: TV
    commands:
      - action: SWITCH_ON
        devices: [ TV ]
  - name: TV Abend
    commands:
      - action: SWITCH_ON
        devices: [ TV, TV Lampe ]
      - action: SHUTTER_DOWN
        tags: WoKüEss
  - name: Guten Morgen
    commands:
      - action: SHUTTER_UP
        tags: [ Unten, NichtBad ]
  - name: Guten Morgen Arbeit
    commands:
      - action: SHUTTER_UP
        tags: [ Unten, NichtSchlaf ]
  - name: Gute Nacht
    commands:
      - action: SHUTTER_DOWN
        tags: [ Unten, Oben ]
      - action: SWITCH_OFF
        devices: [ TV, TV Lampe ]

devices:
  - name: TV
    type: SHELLY1PM
    host: shelly1-BA338D
    tags: [ ]
  - name: TV Lampe
    type: SHELLY1PM
    host: shelly1-BA338A
    tags: [ ]
  - name: Küche links
    type: SHELLY25_SHUTTER
    host: shellyswitch25-687B91
    tags: [ Unten, WoKüEss ]
  - name: Küche rechts
    type: SHELLY25_SHUTTER
    host: shellyswitch25-6886EF
    tags: [ Unten, WoKüEss ]
  - name: EssZi links
    type: SHELLY25_SHUTTER
    host: shellyswitch25-687D3C
    tags: [ Unten, WoKüEss ]
  - name: EssZi rechts
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68DC50
    tags: [ Unten, WoKüEss ]
  - name: WoZi links
    type: SHELLY25_SHUTTER
    host: shellyswitch25-688911
    tags: [ Unten, WoKüEss, Hinten ]
  - name: WoZi mitte
    type: SHELLY25_SHUTTER
    host: shellyswitch25-E8DB84AC60A9
    tags: [ Unten, WoKüEss, Hinten ]
  - name: WoZi rechts
    type: SHELLY25_SHUTTER
    host: shellyswitch25-E8DB84ACB060
    tags: [ Unten, WoKüEss, Hinten ]
  - name: HWR Tür
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68DB9F
    tags: [ Unten, Hinten ]
  - name: HWR Fenster
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68DC82
    tags: [ Unten, Hinten ]
  - name: Gäste
    type: SHELLY25_SHUTTER
    host: shellyswitch25-688DAD
    tags: Unten
  - name: Gäste WC
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68db92
    tags: Unten
  - name: Bad
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68DB2E
    tags: [ Oben, NichtSchlaf ]
  - name: Eltern rechts
    type: SHELLY25_SHUTTER
    host: shellyswitch25-6923BE
    tags: [ Oben, NichtBad ]
  - name: Eltern links
    type: SHELLY25_SHUTTER
    host: shellyswitch25-6926D5
    tags: [ Oben, NichtBad ]
  - name: Kind links
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68DBA5
    tags: [ Oben, NichtBad, NichtSchlaf ]
  - name: Kind rechts
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68DAD0
    tags: [ Oben, NichtBad, NichtSchlaf ]
  - name: Büro
    type: SHELLY25_SHUTTER
    host: shellyswitch25-68DB76
    tags: [ Oben, NichtBad, NichtSchlaf ]


